### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by greg0ire**

### CODE REVIEW

**Comment by greg0ire** [comment]
I don't know why Travis fails…

**Comment by Padam87** [comment]
@greg0ire Tests seem to be working locally. Do you want to add any more commits, or can I merge this?

I think I will spend some time on this bundle when I'm free, haven't used it in a while, and a couple things are very much out of date. This will be a great first step, thanks!

**Comment by greg0ire** [comment]
I am trying to integrate the bundle in an application that uses sonata admin, and I am not done yet, so I might add some more commits. I will tell you when I am done. Anyway, it is great to here you plan on working on this bundle again!

**Comment by Padam87** [comment]
Great! Let me know, if I can help. Are you planning on using the it with schema, or with individual rows?

**Comment by greg0ire** [comment]
I am unsure yet, maybe you can advise :  I have an entity called Library that should hold the schema: a librarian should be able to define various fields that should be filled by the subscribers of the library when they register. Is this a valid use case for the bundle, and if yes what method do you recommend ?

**Comment by Padam87** [comment]
This is very similar to our use case when I created the bundle :) This is the with Schema approach, where defininitions will be applied to all entities.

**Comment by greg0ire** [comment]
Great, I'll go with that then. At the moment, I'm trying to integrate it in a backend that uses Sonata admin, and I don't seem to have a prototype data attribute in my attribute collection widget, I am trying to figure that out, but if you had any hint to give me, that would be great.

**Comment by greg0ire** [comment]
In [this pragraph](https://github.com/Padam87/AttributeBundle/blob/master/Resources/doc/usage_with_schema.md#2-update-your-form), it is unclear what form we are talking about : is it the form where you define the schema, or the form where you fill attributes in a predefined schema ?

**Comment by Padam87** [comment]
The schema itself is created automatically, based on the `@EAV\Entity` annotations in the [SchemaCreatorListener](https://github.com/Padam87/AttributeBundle/blob/master/Listener/SchemaCreatorListener.php), and you can attach definitions to it. If you are using sonata, the `DefinitionAdmin` is propably the best to create first.

After you have created some definitions for your schema, the [AttrubteCreatorListener](https://github.com/Padam87/AttributeBundle/blob/master/Listener/AttributeCreatorListener.php) will add all attributes to your `@EAV\Entity`, based on your definitions.

Sorry, I've been very brief about this (Step6).

The form in step 2 would be the one where you want to input your values, eg the `Subscriber` form in your case.

**Comment by greg0ire** [comment]
Ok, thanks for the explanations, I am going to make that more clear in the docs :)

**Comment by Padam87** [comment]
Awesome, thank you!

**Comment by greg0ire** [comment]
After having a look at the schema creator listener,  I have a doubt : is it possible to have different libraries define different schemas ?

**Comment by greg0ire** [comment]
I'm under the impression that I can have that, but in that case, I should not use the listener. I have created a field named `schema` in my library, and I managed to get a nice widget that allows me to create definition. I think it is not the main usage of this bundle, but I think it might work.

**Comment by Padam87** [comment]
That is not supported unfortunaltely. Our need were system wide, not depending on other entities. You would have to create a $subscriberSchema reference in your Library entity, and apply that to the Subscriber, but the DIExtra bundle makes it hard do owerwite listeners.

**Comment by Padam87** [comment]
I see we have arrived to the same conclusion. :) It would be great to find a way to support this in the bundle, i will look into it in the weekend.

**Comment by greg0ire** [comment]
Ok great! I seem to have the first step (schema definition) effortlessly, I'll tell you if I manage to achieve my goal without twisting things too much.

**Comment by Padam87** [comment]
Thanks.

**Comment by greg0ire** [comment]
Small question : what is the use of the `unit` field ?

**Comment by Padam87** [comment]
It can be ignored. It was added so a definition could be created twice, with different unit of measurement. Propably a bit of overkill, looking back at it now. :)

**Comment by greg0ire** [comment]
Ok thanks, I'll try to hide it later.

**Comment by greg0ire** [comment]
Good news, I managed to do what I want by modifying slightly (but directly, I know it is bad but it is of course temporary) the attribute creator listener like this : 

                /* $schema = $em->getRepository('Padam87AttributeBundle:Schema')->findOneBy(array( */
                /*     'className' => $refl->getName() */
                /* )); */
                $schema = $entity->getLibrary()->getSchema();

                if ($schema !== null) {
                    /* foreach ($schema->getDefinitions() as $definition) { */
                    foreach ($schema as $definition) {

So it is definitely doable.

**Comment by greg0ire** [comment]
I think you can merge.

**Pull request merged**
